version: '3'

services:
  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - ./order/app.env

  payment-service:
    build:
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - ./payment/app.env

  authentication-service:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    depends_on:
      - postgres
    env_file:
      - ./authentication/app.env
  
  merchant-service:
    build:
      context: ./merchant
      dockerfile: Dockerfile
    ports:
      - "8003:8080"
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - ./merchant/app.env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:13
    env_file:
      - ./postgres/app.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: