// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: order.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderGrpc_UpdateInventory_FullMethodName = "/pb.OrderGrpc/UpdateInventory"
)

// OrderGrpcClient is the client API for OrderGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderGrpcClient interface {
	UpdateInventory(ctx context.Context, in *UpdateInventoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type orderGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderGrpcClient(cc grpc.ClientConnInterface) OrderGrpcClient {
	return &orderGrpcClient{cc}
}

func (c *orderGrpcClient) UpdateInventory(ctx context.Context, in *UpdateInventoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OrderGrpc_UpdateInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderGrpcServer is the server API for OrderGrpc service.
// All implementations must embed UnimplementedOrderGrpcServer
// for forward compatibility.
type OrderGrpcServer interface {
	UpdateInventory(context.Context, *UpdateInventoryRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedOrderGrpcServer()
}

// UnimplementedOrderGrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderGrpcServer struct{}

func (UnimplementedOrderGrpcServer) UpdateInventory(context.Context, *UpdateInventoryRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInventory not implemented")
}
func (UnimplementedOrderGrpcServer) mustEmbedUnimplementedOrderGrpcServer() {}
func (UnimplementedOrderGrpcServer) testEmbeddedByValue()                   {}

// UnsafeOrderGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderGrpcServer will
// result in compilation errors.
type UnsafeOrderGrpcServer interface {
	mustEmbedUnimplementedOrderGrpcServer()
}

func RegisterOrderGrpcServer(s grpc.ServiceRegistrar, srv OrderGrpcServer) {
	// If the following call pancis, it indicates UnimplementedOrderGrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderGrpc_ServiceDesc, srv)
}

func _OrderGrpc_UpdateInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderGrpcServer).UpdateInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderGrpc_UpdateInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderGrpcServer).UpdateInventory(ctx, req.(*UpdateInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderGrpc_ServiceDesc is the grpc.ServiceDesc for OrderGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderGrpc",
	HandlerType: (*OrderGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateInventory",
			Handler:    _OrderGrpc_UpdateInventory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
