package rabbitmq

const CREATE_ORDER_COMPLETED_QUEUE = "CREATE_ORDER_COMPLETED_QUEUE"
const E_COM_EXCHANGE = "E_COM_EXCHANGE"
const CREATE_ORDER_ROUTING_KEY = "CREATE_ORDER_QUEUE"

const PAYMENT_ORDER_COMPLETED_QUEUE = "PAYMENT_ORDER_COMPLETED_QUEUE"
const PAYMENT_ORDER_COMPLETED_ROUTING_KEY = "PAYMENT_ORDER_COMPLETED_QUEUE"
