basePath: /api
definitions:
  github_com_VuThanhThien_golang-gorm-postgres_authentication_internal_models_dto.SignInInput:
    properties:
      email:
        example: admin@gmail.com
        type: string
      password:
        example: 123456@Abc
        type: string
    required:
    - email
    - password
    type: object
  github_com_VuThanhThien_golang-gorm-postgres_authentication_internal_models_dto.SignUpInput:
    properties:
      email:
        example: admin@gmail.com
        type: string
      name:
        example: admin
        type: string
      password:
        example: 123456@Abc
        minLength: 8
        type: string
      passwordConfirm:
        example: 123456@Abc
        type: string
      photo:
        type: string
    required:
    - email
    - name
    - password
    - passwordConfirm
    - photo
    type: object
  github_com_VuThanhThien_golang-gorm-postgres_authentication_internal_models_dto.UserListResponse:
    properties:
      total:
        type: integer
      users:
        items:
          $ref: '#/definitions/github_com_VuThanhThien_golang-gorm-postgres_authentication_internal_models_dto.UserResponse'
        type: array
    type: object
  github_com_VuThanhThien_golang-gorm-postgres_authentication_internal_models_dto.UserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      photo:
        type: string
      provider:
        type: string
      role:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is authentication golang server.
  title: Swagger Authentication API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: SignInUser
      parameters:
      - description: Login payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/github_com_VuThanhThien_golang-gorm-postgres_authentication_internal_models_dto.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: SignInUser
      tags:
      - auth
  /auth/logout:
    get:
      consumes:
      - application/json
      description: LogoutUser
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: LogoutUser
      tags:
      - auth
  /auth/refresh:
    get:
      consumes:
      - application/json
      description: RefreshAccessToken
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: RefreshAccessToken
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: SignUpUser
      parameters:
      - description: Register payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/github_com_VuThanhThien_golang-gorm-postgres_authentication_internal_models_dto.SignUpInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_VuThanhThien_golang-gorm-postgres_authentication_internal_models_dto.UserResponse'
      summary: SignUpUser
      tags:
      - auth
  /users/{id}:
    get:
      consumes:
      - application/json
      description: GetUser
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_VuThanhThien_golang-gorm-postgres_authentication_internal_models_dto.UserResponse'
        "500":
          description: an error occurred during the modification
          schema:
            type: string
      security:
      - Bearer: []
      summary: GetUser
      tags:
      - users
  /users/list:
    get:
      consumes:
      - application/json
      description: ListUsers
      parameters:
      - in: query
        name: email
        type: string
      - in: query
        name: name
        type: string
      - in: query
        name: provider
        type: string
      - in: query
        name: role
        type: string
      - default: 10
        example: 5
        in: query
        name: limit
        type: integer
      - default: 1
        example: 1
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_VuThanhThien_golang-gorm-postgres_authentication_internal_models_dto.UserListResponse'
      security:
      - Bearer: []
      summary: ListUsers
      tags:
      - users
  /users/me:
    get:
      consumes:
      - application/json
      description: GetMe
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_VuThanhThien_golang-gorm-postgres_authentication_internal_models_dto.UserResponse'
        "500":
          description: an error occurred during the modification
          schema:
            type: string
      security:
      - Bearer: []
      summary: GetMe
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
